Adding some real backtraces
Ohhh I can now debug my program with *information* instead of monkey
debugging around.

error: index 2 is out of bounds (0,1)
at ciseau.ml:	   53	4 - 31
at ciseau.ml:	   85	91 - 107
at ciseau.ml:	   96	4 - 20
at ciseau.ml:	 1927	29 - 67
at ciseau.ml:	 2128	18 - 61
at ciseau.ml:	 2239	6 - 58
at ciseau.ml:	 2246	6 - 76
at ciseau.ml:	   15	11 - 22
at ciseau.ml:	 2306	9 - 107
at ciseau.ml:	 2340	2 - 16
Raised at file "ciseau.ml", line 20, characters 21-32
Called from file "ciseau.ml", line 2306, characters 9-107

This one indicates a bug in FileviewOp case handler of Tileset.apply_op